version: "3.7"
services:
  goilerplate-local:
    build:
      context: .
      dockerfile: local.Dockerfile
    image: goilerplate:local
    container_name: goilerplate-local
    ports:
      - 3000:80
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_TIMEZONE: Asia/Jakarta
      DBMS: psql
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: goilerplate
      ELASTIC_HOST: http://host.docker.internal
      ELASTIC_PORT: 9200
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      CACHE_DRIVER: redis
      LOG_CHANNEL: file
      PORT: 80
    volumes:
      - .:/app
