version: "3.7"
services:
  goilerplate-local:
    build:
      context: .
      dockerfile: local.Dockerfile
    image: goilerplate:local
    container_name: goilerplate-local
    ports:
      - 80:80
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DBMS: psql
      DB_USER: postgres
      DB_PASSWORD: 
      # DB_HOST: host.docker.internal
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: goilerplate
      PORT: 
    volumes:
      - .:/app
