CREATE TABLE examples (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	bigint_null int8 NULL,
	bigint_not_null int8 NOT NULL,
	integer_null int4 NULL,
	integer_not_null int4 NOT NULL,
	numeric_null numeric(12, 2) NULL,
	numeric_not_null numeric(12, 2) NOT NULL,
	varchar_null varchar(100) NULL,
	varchar_not_null varchar(100) NOT NULL,
	text_null text NULL,
	text_not_null text NOT NULL,
	boolean_null bool NULL,
	boolean_not_null bool NOT NULL,
	date_null date NULL,
	date_not_null date NOT NULL,
	timestamptz_null timestamptz NULL,
	timestamptz_not_null timestamptz NOT NULL,
	timestamp_null timestamp NULL,
	timestamp_not_null timestamp NOT NULL,
	is_active bool NOT NULL DEFAULT true,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz DEFAULT now(),
	deleted_at timestamptz NULL,
	created_by uuid NOT NULL,
	updated_by uuid NULL,
	deleted_by uuid NULL
);